server:
  port: 8080
  servlet:
    context-path: /elevatehub

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elevatehub
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: error
    org.springframework: info
    org.hibernate: info
    com.project.elevatehub: debug
